#https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/
Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-11.0.2/") #(JAVA_HOME PROBLEM)
library(rJava)
library(sf)
library(OpenStreetMap) 
library(tmap)
library(tmaptools)

# Overpass query:
# /*
# This has been generated by the overpass-turbo wizard.
# The original search was:
#    “bar =* in Hamburg”
# */
#    [out:json][timeout:25];
# // fetch area “Hamburg” to search in
# {{geocodeArea:Hamburg}}->.searchArea;
# // gather results
# (
#    // query part for: “bar=*”
#    node["amenity" = "restaurant"](area.searchArea);
#    //way["amenity" = "bar"](area.searchArea);
#    //relation["amenity" = "bar"](area.searchArea);
# );
# // print results
# out body;
# >;
# out skel qt;

# use OSM boundaries to get Hamburg neighborhoods as cover
# 

rm(list = ls())
viertel <- read_sf("./Hamburg_AL10.geojson")
viertel <- viertel[-36,]
bars <- read_sf("./Hamburgbars.geojson")
restaurants <- read_sf("./Hamburgrestaurants.geojson")

viertel <- st_transform(viertel, crs = 2154)
bars <- st_transform(bars, crs = 2154)
restaurants <- st_transform(restaurants, crs = 2154)


bars_density <- smooth_map(bars, bandwidth = 2, cover = viertel)
rest_density <- smooth_map(restaurants, bandwidth = 2, cover = viertel)


pdf("./map.pdf", width = 10, height = 10)
tm_shape(viertel) +
    tm_borders() +
    tm_shape(bars_density$polygons) +
    tm_fill(col = "level", palette = "Blues", title = "Bars density", alpha = 0.5) +
    tm_shape(bars) +
    tm_dots(shape = 16, col = "blue", size = 0.2, alpha = 0.3) +
    tm_shape(rest_density$polygons) +
    tm_fill(col = "level", title = "Restaurant density", alpha = 0.5) +
    tm_shape(restaurants) +
    tm_dots(shape = 16, col = "brown", size = 0.2, alpha = 0.3) +
    tm_style("gray", title = "Density of bars and restaurants in Hamburg") +
    tm_scale_bar(position = c("left", "BOTTOM"))
dev.off()

