#https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/
Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-11.0.2/") #(JAVA_HOME PROBLEM)
library(rJava)
library(sf)
library(OpenStreetMap) 
library(tmap)
library(tmaptools)

# Overpass query:
# /*
# This has been generated by the overpass-turbo wizard.
# The original search was:
#    “bar =* in Hamburg”
# */
#    [out:json][timeout:25];
# // fetch area “Hamburg” to search in
# {{geocodeArea:Hamburg}}->.searchArea;
# // gather results
# (
#    // query part for: “bar=*”
#    node["amenity" = "restaurant"](area.searchArea);
#    //way["amenity" = "bar"](area.searchArea);
#    //relation["amenity" = "bar"](area.searchArea);
# );
# // print results
# out body;
# >;
# out skel qt;

# get water
# /*
#    This has been generated by the overpass-turbo wizard.
# The original search was:
#    “water”
# */
#    [out:json][timeout:25];
# {{geocodeArea:Hamburg}}->.searchArea;
#(
#    // query part for: “water”
#    way["natural"="water"](area.searchArea);
#    relation["natural"="water"](area.searchArea);
#);
#// print results
#out body;
#>;
#out skel qt;

# Wambacher curl code?

rm(list = ls())
viertel <- read_sf("./Hamburg_AL10.geojson")
viertel <- viertel[-36,]
bars <- read_sf("./Hamburgbars.geojson")
restaurants <- read_sf("./Hamburgrestaurants.geojson")
water <- read_sf("./Water.geojson")
dulsberg <- read_sf("./Dulsberg.geojson")
other <- read_sf("./AL4.geojson")

viertel <- st_transform(viertel, crs = 2154)
restaurants <- st_transform(restaurants, crs = 2154)
water <- st_transform(water, crs = 2154)
dulsberg <- st_transform(dulsberg, crs = 2154)
other <- st_transform(other, crs = 2154)

other <- crop_shape(other, viertel)

rest_density <- smooth_map(restaurants, 
                           bandwidth = 0.45, 
                           nlevels = 20,
                           unit = "km")

pdf(file = "./map.pdf", width = 20, height = 20)
tm_shape(viertel) +
    tm_borders() +
    tm_shape(other) +
    tm_fill(col = "chartreuse1") +
    tm_shape(dulsberg) +
    tm_fill(col = "red", alpha = 0.9) +
    tm_shape(rest_density$polygons) +
    tm_fill(col = "level", title = "Restaurants", alpha = 0.8) +
    tm_shape(water) +
    tm_fill(col = "lightblue", alpha = 0.7) +
    tm_style("white", 
             title = "Restaurants in Hamburg") +
    tm_layout(frame = FALSE, 
              legend.show = FALSE, 
              title.size = 4,
              inner.margins = c(0,0),
              title.position = c("left", "top"),
              fontfamily = "mono") +
    tm_credits("Source: OpenStreetMap. Geometry: Wambacher OSM Boundaries. Computed by J. Beley.",
               position = c("left", "bottom"),
               size = 1.5) 
dev.off()