#https://cimentadaj.github.io/blog/2018-05-25-installing-rjava-on-windows-10/installing-rjava-on-windows-10/
Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-11.0.2/") #(JAVA_HOME PROBLEM)
library(rJava)
library(sf)
library(OpenStreetMap) 
library(tmap)
library(tmaptools)

# Overpass query:
# /*
# This has been generated by the overpass-turbo wizard.
# The original search was:
#    “bar =* in Hamburg”
# */
#    [out:json][timeout:25];
# // fetch area “Hamburg” to search in
# {{geocodeArea:Hamburg}}->.searchArea;
# // gather results
# (
#    // query part for: “bar=*”
#    node["amenity" = "restaurant"](area.searchArea);
#    //way["amenity" = "bar"](area.searchArea);
#    //relation["amenity" = "bar"](area.searchArea);
# );
# // print results
# out body;
# >;
# out skel qt;

# use OSM boundaries to get Hamburg neighborhoods as cover

rm(list = ls())
viertel <- read_sf("./Hamburg_AL10.geojson")
viertel <- viertel[-36,]
bars <- read_sf("./Hamburgbars.geojson")
restaurants <- read_sf("./Hamburgrestaurants.geojson")
water <- read_sf("./Water.geojson")

viertel <- st_transform(viertel, crs = 2154)
restaurants <- st_transform(restaurants, crs = 2154)
water <- st_transform(water, crs = 2154)

rest_density <- smooth_map(restaurants, bandwidth = 0.45, nlevels = 20)

tm_shape(viertel) +
    tm_borders(col = "grey30") +
    tm_fill(col = "chartreuse1", alpha = 0.15) +
    tm_shape(rest_density$polygons) +
    tm_fill(col = "level", title = "Restaurants", alpha = 0.8) +
    tm_shape(water) +
    tm_fill(col = "lightblue", alpha = 0.7) +
    tm_style("white", 
             title = "Restaurants in Hamburg") +
    tm_layout(frame = FALSE,
              legend.outside = TRUE)



# get water
# /*
#    This has been generated by the overpass-turbo wizard.
# The original search was:
#    “water”
# */
#    [out:json][timeout:25];
# {{geocodeArea:Hamburg}}->.searchArea;
#(
#    // query part for: “water”
#    way["natural"="water"](area.searchArea);
#    relation["natural"="water"](area.searchArea);
#);
#// print results
#out body;
#>;
#out skel qt;